<a href="https://colab.research.google.com/github/arjunsumina/analytics_code/blob/main/artificial_intelligence_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---------------------------------
1. Understanding Numpy ND array

1.   Basic Neural Networks
2.   Deep Neural Networks

---------------------------------





1. Understanding Numpy ND array

In [14]:
# shape gives the length of the array in each direction
# dimension gives the number of dimensions
# understanding 1 dimensional numpy nd arrays
print('1d array')
a_1d = np.arange(3)
print(a_1d)
print(a_1d.ndim)
print(a_1d.shape)
print(a_1d.size)
# understanding 2 dimensional numpy nd arrays
print('2d array')
a_2d = np.arange(12).reshape((3, 4))
print(a_2d)
print(a_2d.ndim)
print(a_2d.shape)
print(a_2d.size)
# understanding 3 dimensional numpy nd arrays
print('3d array')
a_3d = np.arange(24).reshape((2, 3, 4))
print(a_3d)
print(a_3d.ndim)
print(a_3d.shape)
print(a_3d.size)



1d array
[0 1 2]
1
(3,)
3
2d array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
(3, 4)
12
3d array
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3
(2, 3, 4)
24


In [21]:
# implementing and gate using perceptron
# declare the set of inputs as numpy array
# the four sets of two binary inputs are x1,x2
# The bias term has been set as 0.
# the three weights are 0,0,0
# the four outputs are 0,0,0,1
import numpy as np
x = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
print('input x is',x)
print('dimension of x',x.ndim)
print('shape of x',x.shape)
print('size of x',x.size)
y = np.array([0, 0, 0, 1])
print('output y is',y)
print('dimension of y',y.ndim)
print('shape of y',y.shape)
print('size of y',y.size)
w = np.array([0.0, 0.0, 0.0])
print('input w is',w)
print('dimension of w',w.ndim)
print('shape of w',w.shape)
print('size of w',w.size)


input x is [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
dimension of x 2
shape of x (4, 3)
size of x 12
output y is [0 0 0 1]
dimension of y 1
shape of y (4,)
size of y 4
input w is [0. 0. 0.]
dimension of w 1
shape of w (3,)
size of w 3


In [27]:
# heaviside function is the unit step function
# if the input to the heaviside function is greater than zero, output is 1
# if the input to the heaviside function is lower than zero, output is 0.
# if the input to the heaviside function is equal to zero, output can be set to
# user requirements
# number of iterations = 100
# learning rate = .5
# for "number of iterations", we feed the neural network with the four sets
# of inputs and check the difference of the expected ouptut and predicted output
# for each input combination, we compute the error and update all the weights
# in the neural network.
x = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
y = np.array([0, 0, 0, 1])
w = np.array([0.0, 0.0, 0.0])

eta = 0.5
print(w)
print(y.ndim)
for t in range(10000):
    for i in range(len(y)):
        y_pred = np.heaviside(np.dot(x[i], w), 0)
        error = y[i] - y_pred
        w +=  error * eta * x[i]
        #print(w)

print('weight')
print(w)






[0. 0. 0.]
1
weight
[ 1.   0.5 -1. ]


faster way of implementing an and gate using matrix method
in the above case,weight updation was done for each combination for input
but now we update the weight only once for every 4 sets of input combinations of the and gate bold


In [28]:
import numpy as np
x = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
y = np.array([0, 0, 0, 1])
w = np.array([0.0, 0.0, 0.0])
eta = 0.5
for t in range(10000):
    y_pred = np.heaviside(np.dot(x, w), 0)
    w += np.dot((y - y_pred), x)
print(w)

[ 1.  1. -1.]


In [47]:
# nand gate with sigmoid function
# defining sigmoid function
def sigmoid(v):
    return 1.0 / (1 + np.exp(-v))

import numpy as np
x = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
y = np.array([1.0, 1.0, 1.0, 0.0])
weight = np.array([0.0, 0.0, 0.0])

eta = 0.5
for t in range(100):
    y_pred = sigmoid(np.dot(x, weight))
    sigmoid_derivative = np.dot(y_pred,1-y_pred)
    #weight += np.dot((y - y_pred), x)
    weight += np.dot(np.dot((y - y_pred), x),sigmoid_derivative)
    #print(weight)


y_pred = sigmoid(np.dot(x, weight))
print(y_pred)


[0. 0. 1.]
[-0.36343099 -0.36343099  1.05958575]
[-0.58280338 -0.58280338  1.35848403]
[-0.77885947 -0.77885947  1.60009815]
[-0.94580114 -0.94580114  1.81855174]
[-1.09273432 -1.09273432  2.01274185]
[-1.22336796 -1.22336796  2.18811038]
[-1.34097745 -1.34097745  2.347832  ]
[-1.44793474 -1.44793474  2.49449411]
[-1.54604105 -1.54604105  2.63010603]
[-1.63668352 -1.63668352  2.75625493]
[-1.72094882 -1.72094882  2.87421076]
[-1.79970196 -1.79970196  2.98500298]
[-1.87364173 -1.87364173  3.08947652]
[-1.94334028 -1.94334028  3.18833287]
[-2.00927178 -2.00927178  3.28216069]
[-2.07183358 -2.07183358  3.37145874]
[-2.13136197 -2.13136197  3.45665338]
[-2.18814414 -2.18814414  3.53811205]
[-2.24242737 -2.24242737  3.61615373]
[-2.2944262  -2.2944262   3.69105723]
[-2.34432798 -2.34432798  3.76306774]
[-2.39229738 -2.39229738  3.83240208]
[-2.43847993 -2.43847993  3.89925306]
[-2.48300495 -2.48300495  3.96379286]
[-2.52598789 -2.52598789  4.02617601]
[-2.56753227 -2.56753227  4.08654169]
[

In [53]:
# or gate with sigmoid function
# defining sigmoid function
def sigmoid(v):
    return 1.0 / (1 + np.exp(-v))

import numpy as np
x = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
y = np.array([0.0, 0.0, 0.0, 1.0])
weight = np.array([0.0, 0.0, 0.0])

eta = 0.5
for t in range(100):
    y_pred = sigmoid(np.dot(x, weight))
    sigmoid_derivative = np.dot(y_pred,1-y_pred)
    #weight += np.dot((y - y_pred), x)
    weight += np.dot(np.dot((y - y_pred), x),sigmoid_derivative)
    #print(weight)


y_pred = sigmoid(np.dot(x, weight))
print(y_pred)

[0.00181257 0.0968061  0.0968061  0.86350859]
